#pragma once

#define VERSION_MAJOR 2
#define VERSION_MINOR 2
#define VERSION_PATCH 0
#define VERSION_TYPE "DEV"

#define VERSION_STRING #VERSION_MAJOR "." #VERSION_MINOR "." #VERSION_PATCH " " VERSION_TYPE

#define ERROR_EXIT_CODE 0xBEDECADE